name: Continuous Deployment

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

    
      - name: Set up SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3  

        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  

     
      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@16.170.245.117 << 'EOF'
            
            cd /home/ubuntu/hng12-stage2-fastapi-book-project

            git pull origin main

            source /home/ubuntu/hng12-stage2-fastapi-book-project/venv/bin/activate

            pip install -r requirements.txt

            sudo systemctl restart fastapi.service

            sudo systemctl restart nginx

          EOF
          
          
