name: Continuous Integration

on:
  pull_request:
    branches:
      - main  # The workflow will run on PRs to the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest  # The environment where the CI job will run

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.2'  # Use your desired Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests using pytest
      - name: Run tests
        run: |
          pytest  # Ensure pytest is installed, this will run your tests
